name: Portishead
twitter:
    key: CONSUMER_KEY
    secret: CONSUMER_SECRET
deploy:
    application: portishead
social:
    twitter: USERNAME
    flickr: USERNAME
    dribbble: USERNAME
    github: USERNAME
    linkedin: /in/USERNAME  
# Uncomment below to enable Google Analytics tracking
# google_analytics: UA-PROPERTY-_ID
