require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CategoriesController do

  def mock_category(stubs={})
    @mock_category ||= mock_model(Category, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all categories as @categories" do
      Category.stub(:all) { [mock_category] }
      get :index
      assigns(:categories).should eq([mock_category])
    end
  end

  describe "GET show" do
    it "assigns the requested category as @category" do
      Category.stub(:find).with("37") { mock_category }
      get :show, :id => "37"
      assigns(:category).should be(mock_category)
    end
  end

end

describe CategoriesController, "as admin" do
  render_views

  def mock_category(stubs={})
    @mock_category ||= mock_model(Category, stubs).as_null_object
  end
  
  def mock_user(stubs={})
    @mock_user ||= mock_model(User, stubs).as_null_object
  end
  
  before(:each) do
    user = Factory(:user)
    session[:user_id] = user.id
  end
  
  it "should render new template on new action" do
    get :new
    response.should render_template(:new)
  end
  
  it "should render edit template on edit action" do
    category = Factory(:category)
    get :edit, :id => category.id
    response.should render_template(:edit)
  end

end
